# Generated by Django 3.2 on 2021-04-27 07:29

from django.db import migrations
import image_optimizer.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='Icon',
            field=image_optimizer.fields.OptimizedImageField(blank=True, default='avatar.png', null=True, upload_to='images/'),
        ),
    ]
