# Generated by Django 3.2 on 2021-04-27 08:24

from django.db import migrations
import image_optimizer.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_usermodel_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='Icon',
            field=image_optimizer.fields.OptimizedImageField(default='avatar.jpg', upload_to='images/'),
        ),
    ]
