# Generated by Django 3.2 on 2021-04-27 14:23

from django.db import migrations, models
import image_optimizer.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_usermodel_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='pushNotifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('body', models.EmailField(max_length=50)),
                ('Icon', image_optimizer.fields.OptimizedImageField(default='avatar.jpg', upload_to='images/')),
            ],
        ),
    ]
