# Generated by Django 3.2 on 2021-04-27 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_pushnotifications'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pushnotifications',
            name='body',
            field=models.CharField(max_length=50),
        ),
    ]
