# Generated by Django 3.2 on 2021-04-27 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_alter_pushnotifications_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pushnotifications',
            old_name='Icon',
            new_name='Image',
        ),
    ]
